# Generated by Django 4.2.9 on 2024-01-13 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Место выполнения')),
                ('time', models.DateTimeField(verbose_name='Время выполнения')),
                ('action', models.CharField(max_length=150, verbose_name='Действие')),
                ('pleasant', models.BooleanField(default=False, verbose_name='Признак приятности')),
                ('periodisity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность(в днях)')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('complete_time', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время выполнения')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публикации')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
